# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import subprocess
import sys, os, time
from github import Github
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartDialog(object):
    def setupUi(self, StartDialog):
        StartDialog.setObjectName("StartDialog")
        StartDialog.resize(318, 364)
        self.label = QtWidgets.QLabel(StartDialog)
        self.label.setGeometry(QtCore.QRect(0, -10, 321, 331))
        self.label.setObjectName("label")
        self.StartButton = QtWidgets.QPushButton(StartDialog)
        self.StartButton.setGeometry(QtCore.QRect(0, 320, 111, 41))
        self.StartButton.setObjectName("StartButton")
        self.StartButton.clicked.connect(self.OnStart)
        self.StopButton = QtWidgets.QPushButton(StartDialog)
        self.StopButton.setGeometry(QtCore.QRect(110, 320, 91, 41))
        self.StopButton.setObjectName("StopButton")
        self.StartButton.clicked.connect(self.OnStop)
        self.UpdateButton = QtWidgets.QPushButton(StartDialog)
        self.UpdateButton.setGeometry(QtCore.QRect(210, 320, 101, 41))
        self.UpdateButton.setObjectName("UpdateButton")
        self.StartButton.clicked.connect(self.OnUpdate)

        self.retranslateUi(StartDialog)
        QtCore.QMetaObject.connectSlotsByName(StartDialog)

    def retranslateUi(self, StartDialog):
        _translate = QtCore.QCoreApplication.translate
        StartDialog.setWindowTitle(_translate("StartDialog", "FLASK POS"))
        self.label.setText(_translate("StartDialog", "<html><head/><body><p><img src=\"logo-neu.png\"/></p></body></html>"))
        self.StartButton.setText(_translate("StartDialog", "Start"))
        self.StopButton.setText(_translate("StartDialog", "Stop"))
        self.UpdateButton.setText(_translate("StartDialog", "update"))

    def OnStart(self):
        subprocess.Popen(['bash', 'flaskpos_dev.sh'])
        time.sleep(8)
        os.system("firefox-esr http://localhost:8000 -kiosk")

    def OnStop(self):
        subprocess.Popen.terminate()
        sys.exit()

    def OnUpdate(self):
        os.system('git pull https://github.com/aboro72/flask-pos.git')


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_StartDialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
